### ISSUE TITLE
set dnsSettings get timeout exception

### ISSUE THREAD

**Issue by denonzhu** [Tienisto/rhttp#39] opened 2024-11-22 08:57 UTC
<img width="498" alt="image" src="https://github.com/user-attachments/assets/18088c86-b144-4d5a-b64c-0851c8b6e4f4">
<img width="1256" alt="image" src="https://github.com/user-attachments/assets/40d0a550-61bf-4315-bc57-604de1ea714b">
if remove dnsSetting can work

**Comment by nkxingxh** [comment] 2024-11-30 09:23
I also encountered this problem and after checking, it was confirmed that the rhttp library was causing the problem.

The specific questions are in the following lines

https://github.com/Tienisto/rhttp/blob/51135a3a88fb9d29c1cafa07617d5079efceb7b2/rhttp/rust/src/api/client.rs#L15
https://github.com/Tienisto/rhttp/blob/51135a3a88fb9d29c1cafa07617d5079efceb7b2/rhttp/rust/src/api/client.rs#L250
https://github.com/Tienisto/rhttp/blob/51135a3a88fb9d29c1cafa07617d5079efceb7b2/rhttp/rust/src/api/client.rs#L263

Since the port `DUMMY_PORT=1111` was pre-defined in the rhttp library and `SocketAddr` was created with it, it ended up not connecting to the server correctly.

Solution (either one).
1. change `DUMMY_PORT` to 80 or 443 (your server port)
2. change both `{ip}:{DUMMY_PORT}` to `{ip}` and change your `DnsSettings` to return an address that includes the port, e.g. `10.20.30.40:443`.

**Comment by Tienisto** [comment] 2024-11-30 19:28
Fixed in `v0.9.4`

**Closed by Tienisto** 2024-11-30 19:28 UTC
